### ISSUE TITLE
KeyError: 'kgs_username' during signup 

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#234]
```
[12/Jan/2018 04:09:04] ERROR [django.request:135] Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/allauth/account/views.py", line 177, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/allauth/account/views.py", line 65, in dispatch
    **kwargs)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/allauth/account/views.py", line 155, in dispatch
    **kwargs)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/allauth/account/views.py", line 80, in post
    if form.is_valid():
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "/home/climu/osr/venv/lib/python3.5/site-packages/allauth/account/forms.py", line 340, in clean
    super(SignupForm, self).clean()
  File "/home/climu/osr/venv/lib/python3.5/site-packages/allauth/account/forms.py", line 306, in clean
    cleaned_data = super(BaseSignupForm, self).clean()
  File "/home/climu/osr/openstudyroom/league/forms.py", line 51, in clean
    if not (self.cleaned_data['kgs_username'] or self.cleaned_data['ogs_username']):
KeyError: 'kgs_username'
```

**Comment by climu** [comment]
I canot manage to reproduce locally :(

This one is quite bad since it probably forbid user to register OSR.

**Comment by climu** [comment]
I think I got it!

Someone is sending at 15 lenght kgs_username where

```
class LeagueSignupForm(forms.Form):
    kgs_username = forms.CharField(max_length=10, required=False)
```
In Firefox and Chrome I canot type more than 10 characters for this fields. Could it be that the user is using a deprecated browser?

Mind that this very user is not providing neither a valid KGS nor a valid OGS usernames.
