### ISSUE TITLE
decimal.Decimal' object has no attribute 'startswith' at check_validity

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#235]
```
Traceback (most recent call last):
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/climu/osr/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/climu/osr/openstudyroom/league/views.py", line 108, in scraper_view
    out = scraper()
  File "/home/climu/osr/openstudyroom/league/views.py", line 79, in scraper
    valid_events = sgf.check_validity()
  File "/home/climu/osr/openstudyroom/league/models.py", line 474, in check_validity
    check = self.check_validity_event(event)
  File "/home/climu/osr/openstudyroom/league/models.py", line 440, in check_validity_event
    if not self.komi.startswith('6.5'):
AttributeError: 'decimal.Decimal' object has no attribute 'startswith'

```

**Comment by climu** [comment]
Strange thing is locally when I `print(type(self.komi))` I got `<class 'str'>` but  we define komi as:
`   komi = models.DecimalField(default=6.5, max_digits=5, decimal_places=2)`

For now, I will just `if not str(self.komi.startswith('6.5')):`

But why can it be str sometimes and decimal sometimes?
